#-------------------------------
# General Site Settings
title: Woj Training Systems
logo: # You can add own logo. For example '/images/logo.png'.
description: Woj Training Systems is owned by Jake Wojciechowski, a professional natural bodybuilder and NASM certified personal trainer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wojtrainingsystems.github.io" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# Author Settings
author:
  name: Woj Training Systems
  bio: Jake Wojciechowski is a professional natural bodybuilder, NASM certified personal trainer, and a registered and licensed orthopedic occupational therapist. He holds a Bachelor of Science degree in kinesiology and a Master of Science degree in Occupational Therapy. Jake has been training individuals for 5+ years in person and online. He's trained a wide demographic of clients, ranging from CVA survivors to IFBB professional bodybuilders.
  avatar: '/images/jake/Jake1.jpeg'

social:
#- {icon: "ion-logo-twitter", label: Twitter, link: "https://twitter.com"}
- {icon: "ion-logo-facebook", label: Facebook, link: "https://www.facebook.com/jake.wojciechowski.5"}
# - {icon: "ion-logo-pinterest", label: Pinterest, link: "https://pinterest.com"}
# - {icon: "ion-logo-dribbble", label: Dribbble, link: "https://dribbble.com"}
- {icon: "ion-logo-instagram", label: Instagram, link: "https://www.instagram.com/wojtrainingsystems/?hl=en"}
# - {icon: "ion ion-logo-vimeo", label: Vimeo, link: "https://vimeo.com"}

# Example of adding a new link to the author section and footer - {icon: "ion-logo-github", label: Github, link: "https://github.com"}
# Other icons can be found at https://ionicons.com/v4/

#-------------------------------
# Hero Settings
hero:
  hero__title: Welcome to Woj Training Systems.
  hero__description: Jake Wojciechowski is a professional natural bodybuilder, NASM certified personal trainer, and a registered and licensed orthopedic occupational therapist. He holds a Bachelor of Science degree in kinesiology and a Master of Science degree in Occupational Therapy. Jake has been training individuals for 5+ years in person and online. He's trained a wide demographic of clients, ranging from CVA survivors to IFBB professional bodybuilders.
  hero__image: '/images/jake/Jake1.jpeg'


#-------------------------------
# Newsletter (_includes/footer-widgets/widget-subscribe.html)
# mailchimp: true # To enable the mailchimp form, use the value 'true'. To disable the form, use the value 'false' or leave the field blank.
# mailchimp__title: Get interesting news # Add your Title
# mailchimp__text: Subscribe to our newsletter and we’ll send you the emails of latest posts. # Add your description.
# mailchimp__identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
# mailchimp__button__text: Join # Add your button text


#-------------------------------
# Contact Settings
contact:
  email: /f/xlezewob # Add your email for contact form
  description: Please complete this form if you are interested in joining the Woj Training Systems Team as a client or athlete. I will review your inquiry and get back to you ASAP.


#-------------------------------
# Comment Section (Disqus)
# disqus-identifier: anvodstudio-demo # add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
# google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 5
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  /:title

sass:
  sass_dir: _sass
  style: compressed
